config/routes.rb
KnightsChess::Application.routes.draw do
  devise_for :users
  root 'games#index'
  resources :games do
    resources :pieces, only: [:show, :update]
    member do
      put :forfeit
    end
  end
  resources :players, only: [:index, :edit, :update, :show] do
    collection do
      put :delete_user
      put :change_nickname
    end
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  scope :available, -> { where('player_white_id IS NULL OR player_black_id IS NULL') }
  enum status: [:open, :active, :check, :checkmate, :forfeit, :draw]
  enum turn: [:white, :black, :off]

  belongs_to :user
  has_many :pieces
  belongs_to :user
  after_create :populate_board!

  def forfeit(current_player_id)
    if current_player_id == player_white_id
      update_attributes(winning_player_id: player_black_id, status: 'forfeit')
    else
      update_attributes(winning_player_id: player_white_id, status: 'forfeit')
    end
  end

  def in_check?(king)
    king = pieces.find_by(type: 'King')
    pieces.each do |piece|
      return true if piece.valid_move?(king.x_coordinate, king.y_coordinate)
    end
    false
  end

  def stalemate?(king)
    # if king is not in check and unable to move to a safe square
    # the King is stalemated and game is drawn
    king = pieces.find_by(type: 'King')
    return false if in_check?(king) # king cannot be in check
    # binding.pry
    pieces.each do |piece|
      return false if piece.valid_move?(king.x_coordinate, king.y_coordinate) && !in_check?(king)
    end
    true # no valid moves, king not in_chcek stalemate!
  end

  def board_state
    board = []
    pieces.each do |piece|
      board << [piece.x_coordinate, piece.y_coordinate]
    end
    board
  end

  def checkmate?(color)
    if color == 'black'
      pieces.black.each do |piece|
        (0..7).each do |x|
          (0..7).each do |y|
            next unless piece.valid_move? # check every possible valid move
            old_x = piece.x_coordinate
            old_y = piece.y_coordinate
            piece.move_to!(x, y)
            if in_check?(black) == false # check to see if check is still true
              return false # return false if check becomes false
            end
            piece.move_to!(old_x, old_y)
          end
        end
      end
    elsif color == 'white'
      pieces.white.each do |piece|
        (0..7).each do |x|
          (0..7).each do |y|
            next unless piece.valid_move? # check every possible valid move
            old_x = piece.x_coordinate
            old_y = piece.y_coordinate
            piece.move_to!(x, y)
            if in_check?(white) == false # check to see if check is still true
              return false # return false if check becomes false
            end
            piece.move_to!(old_x, old_y)
          end
        end
      end
    end
    true # return true if no move could remove check
  end

  private

  def populate_board!
    # WHITE pieces (bottom)
    # rook: [0,0],[7,0]; knight: [1,0],[6,0]; bishop: [2,0][5,0]; queen: [3,0]; king[4,0]
    # pawns: [0->7,1]
    # BLACK pieces (top)
    # rook: [0,7],[7,7]; knight: [1,7],[6,7]; bishop: [2,7][5,7]; queen: [3,7]; king[4,7]
    # pawns: [0->7,6]
    # white: 0, black: 1
    create_non_pawn_pieces(0)
    create_non_pawn_pieces(1)
    create_pawn_pieces(0)
    create_pawn_pieces(1)
  end

  def create_non_pawn_pieces(color)
    non_pawn_pieces = [
      pieces.new(x_coordinate: 0, type: 'Rook'),
      pieces.new(x_coordinate: 1, type: 'Knight'),
      pieces.new(x_coordinate: 2, type: 'Bishop'),
      pieces.new(x_coordinate: 3, type: 'Queen'),
      pieces.new(x_coordinate: 4, type: 'King'),
      pieces.new(x_coordinate: 5, type: 'Bishop'),
      pieces.new(x_coordinate: 6, type: 'Knight'),
      pieces.new(x_coordinate: 7, type: 'Rook')
    ]
    if color == 0
      non_pawn_pieces.each do |piece|
        piece.update_attributes(y_coordinate: 0, color: color)
      end
    elsif color == 1
      non_pawn_pieces.each do |piece|
        piece.update_attributes(y_coordinate: 7, color: color)
      end
    end
  end

  def create_pawn_pieces(color)
    pawn_pieces = []
    (0..7).each do |n|
      pawn_pieces << pieces.new(x_coordinate: n, type: 'Pawn')
    end
    if color == 0
      pawn_pieces.each do |piece|
        piece.update_attributes(y_coordinate: 1, color: color)
      end
    elsif color == 1
      pawn_pieces.each do |piece|
        piece.update_attributes(y_coordinate: 6, color: color)
      end
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include GamesHelper

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def forfeit
    return render_not_found(:forbidden) if current_user.id != current_game.player_white_id && current_user.id != current_game.player_black_id
    return render_not_found(:forbidden) if game_is_open
    current_game.forfeit(current_user.id)
    render text: "Game forfeit by #{current_user.username} --  #{User.find(current_game.winning_player_id).username} wins!"
    # redirect_to game_path(current_game)
  end

  def new
    @game = Game.new
  end

  def create
    if params[:color].to_i == 1
      params[:game][:player_white_id] = current_user.id
    else
      params[:game][:player_black_id] = current_user.id
    end
    @game = Game.create(game_params)
    redirect_to game_path(@game)
  end

  def show
    return render_not_found if current_game.blank?
  end

  def edit
    return render_not_found(:forbidden) if current_user.id != current_game.user_id
  end

  # to join game as another user, or update game name if user created game
  # rubocop:disable Metrics/AbcSize
  def update
    if current_user.id != current_game.user_id && game_is_open
      current_game.update_attributes(game_params)
      flash.notice = 'You have successfully joined the game!'
      redirect_to game_path(current_game)
    elsif current_user.id == current_game.user_id
      if params[:on_edit_page] == 'yes'
        current_game.update_attributes(game_params)
        flash.notice = 'Game name changed!'
        redirect_to game_path(current_game)
      else
        flash.alert = 'You are the host of this game!'
        redirect_to root_path
      end
    else
      return render_not_found(:forbidden)
    end
  end
  # rubocop:enable Metrics/AbcSize

  def destroy
    if !current_user.nil? && current_user.admin?
      current_game.destroy
      redirect_to players_path
    else
      return render_not_found(:forbidden) if current_user.id != current_game.user_id
      return render_not_found(:forbidden) unless game_is_open
      current_game.destroy
      redirect_to player_path(current_user)
    end
  end

  private

  def current_game
    @current_game = Game.find(params[:id])
  end
  helper_method :current_game

  def game_params
    params.require(:game).permit(
      :name, :player_black_id, :player_white_id, :status, :user_id, :turn, 
      :can_castle_w_ks, :can_castle_w_qs, :can_castle_b_ks, :can_castle_b_qs
    )
  end

  def game_is_open
    current_game.player_white_id.nil? || current_game.player_black_id.nil?
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def render_piece(game, x, y)
    piece = game.pieces.find_by(x_coordinate: x, y_coordinate: y)
    choice = piece.type unless piece.nil?

    # https://en.wikipedia.org/wiki/Chess_symbols_in_Unicode
    white_king = "\u2654".encode('utf-8')
    white_queen = "\u2655".encode('utf-8')
    white_rook = "\u2656".encode('utf-8')
    white_bishop = "\u2657".encode('utf-8')
    white_knight = "\u2658".encode('utf-8')
    white_pawn = "\u2659".encode('utf-8')
    black_king = "\u265A".encode('utf-8')
    black_queen = "\u265B".encode('utf-8')
    black_rook = "\u265C".encode('utf-8')
    black_bishop = "\u265D".encode('utf-8')
    black_knight = "\u265E".encode('utf-8')
    black_pawn = "\u265F".encode('utf-8')

    case choice
    when 'Rook'
      piece.white? ? white_rook : black_rook
    when 'Knight'
      piece.white? ? white_knight : black_knight
    when 'Bishop'
      piece.white? ? white_bishop : black_bishop
    when 'Queen'
      piece.white? ? white_queen : black_queen
    when 'King'
      piece.white? ? white_king : black_king
    when 'Pawn'
      piece.white? ? white_pawn : black_pawn
    end
  end

  def player(color)
    if color == 'white' && current_game.player_white_id.present?
      User.find(current_game.player_white_id)
    elsif color == 'black' && current_game.player_black_id.present?
      User.find(current_game.player_black_id)
    end
  end

  def piece_id(x, y)
    piece = find_piece_by_coordinates(x, y)
    return piece.id if piece.present?
  end

  def piece_color(x, y)
    piece = find_piece_by_coordinates(x, y)
    return piece.color if piece.present?
  end

  def piece_type(x, y)
    piece = find_piece_by_coordinates(x, y)
    return piece.type if piece.present?
  end

  def gravatar_class(color)
    color == current_game.turn ? 'gravatar-box highlight-turn' : 'gravatar-box'
  end

  # return pieces#show url for a specific piece
  def update_url(x, y)
    game_piece_path(current_game, piece_id(x, y)) if piece_id(x, y).present?
  end

  private

  def find_piece_by_coordinates(x, y)
    current_game.pieces.find_by(x_coordinate: x, y_coordinate: y)
  end
end

app/views/games/index.html.erb
  <div class="chess_bg">
    
      <div class="frosty text-center col-md-8 col-md-offset-2">
        <h1>KNIGHTS of REN<h1>
        <!--h2>Create New Game</h2-->
          <% if user_signed_in? %>
            <h3><%= link_to "Create New Chess Game", new_game_path %></h4>
          <% else %>
            <h3><%= link_to "Create New Chess Game", new_user_session_path %></h4>
          <% end %>
        <br />
      </div>

      <div class="games-list text-center col-md-8 col-md-offset-2">
        <div class="col-sm-6">
          <h2>Available Games</h2>
          <br />
          <% @games.available.each do |game| %>
            <h4><%= game.name %></h4>
            <%= simple_form_for game, :url => game_path(game), :method => :put do |f| %>
                <% game.player_white_id.present? ? color = 'black' : color = 'white' %>
                <%= f.hidden_field "player_#{color}_id".to_sym, value: current_user.id if user_signed_in? %>
                <%= f.hidden_field :status, value: 'active' %>
                <%= f.submit "Join Game (as #{color})", class: "btn btn-default btn-sm" %>
            <% end %>    
          <% end %>
          <br />
        </div>


        <div class="col-sm-6">
          <h2>All Games</h2>
          <br />
          <% @games.each do |game| %>
            <h4><%= link_to game.name, "#{game_path(game)}#chess-game" %></h4>
          <% end %>
        </div>
      </div>

      <div class="game-info-section col-md-12">
        <div class="game-info col-md-8 col-md-offset-2">
          <br /><br /><br />
          <h2>Backstory</h2>
          <br />
          <p>Some time ago we all decided to code and as we did we ended up making some pretty cool stuff. For the most part, the venture was a solo trek until we each decided to take the opportunity to join a few others on the same journey and make a chess app.<br /><br />
          
          Why Chess?<br /><br />

          <i>You pick up a pawn. Do you move it one square or two? Wait, is it your first move or second? Oh, there's an opposing piece in a diagonal spot. Will you capture it? But, hold on would that move put your king in check?</i><br /><br />
          If you've ever played Chess-- you get it. If you haven't-- <a href="http://www.chesscorner.com/tutorial/learn.htm" >check this out</a>.<br /><br />
          [TL;DR] Chess has alot going on and the logic it requires made it the perfect choice to continue forging those Ruby skills of ours. And so, *drumroll* we present to you-- Knights of Ren.<br /><br />

          Knights of Ren is a Ruby on Rails chess app led into creation using <i>"red/green/refactor"</i> Test Driven Development (TDD). With the team spanning across the states we kept it agile making excellent use of Trello and Slack in order to keep everyone on the same page regarding tasks. We kept our code seamless in structure thanks to Rubocop, swatted bugs with Pry, collaborated with Git pull requests, and (of course) made sure to <i>"ship early, ship often".</i></p>
          <br /><br /><br />

        <div class="game-tools-section col-md-10 col-md-offset-1">
          <div class="row">
            <div class="tools col-sm-4">
              <%= link_to 'https://github.com/' do %>
                <%=image_tag 'github.png'%>
              <% end %>
            </div>

            <div class="tools col-sm-4">
              <%= link_to 'https://trello.com/' do %>
                <%=image_tag 'trello.png'%>
              <% end %>
            </div>

             <div class="tools col-sm-4">
              <%= link_to 'https://slack.com/' do %>
                <%=image_tag 'slack.png'%>
              <% end %>
            </div>
          </div>
          
          <br /><br />

            <div class="row">
             <div class="tools col-sm-4 col-sm-push-4">
              <%= link_to 'http://batsov.com/rubocop/' do %>
                <%=image_tag 'rubocop2.png'%>
              <% end %>
            </div>
          </div>

           <br /><br />
          
          <div class="row">
            <div class="tools col-sm-4">
              <%= link_to 'http://rspec.info/' do %>
                <%=image_tag 'rspec.png'%>
              <% end %>
            </div>

            <div class="tools col-sm-4">
              <%= link_to 'http://pryrepl.org/' do %>
                <%=image_tag 'pry.png'%>
              <% end %>
            </div>

            <div class="tools col-sm-4">
              <%= link_to 'https://travis-ci.org/' do %>
                <%=image_tag 'travis.png'%>
              <% end %>
            </div>
          </div>

          <br /><br /><br/>
        </div>

        </div>
      </div>

      <div class="team-info text-center col-md-8 col-md-offset-2">
        <br /><br /><br />
        <h2>Behind the Scenes</h2>
        <br />
          <div class="row">
            <div class="team-member col-sm-4">
              <%= link_to 'https://github.com/ats89' do %>
                <%=image_tag 'anthony.png'%>
              <% end %>
              <p>Anthony Sin</p>
            </div>

            <div class="team-member col-sm-4">
              <p>Team Lead</p>
              <%= link_to 'https://github.com/mscoutermarsh' do %>
                <%=image_tag 'mike.jpg'%>
              <% end %>
              <p>Mike Coutermarsh</p>
            </div>
        

            <div class="team-member col-sm-4">
              <%= link_to 'https://github.com/Skjamal' do %>
                <%=image_tag 'satinder.jpg'%>
              <% end %>
              <p>Satinder Jamal</p>
            </div>
          </div>

          <div class="row">
            <div class="team-member col-sm-6">
              <%= link_to 'https://github.com/doyouthunderstand' do %>
                <%=image_tag 'brandon.png'%>
              <% end %>
              <p>Brandon Gorman</p>
            </div>

            <div class="team-member col-sm-6">
              <%= link_to 'https://github.com/rebelcl0ud' do %>
                <%=image_tag 'jovanka.png'%>
              <% end %>
              <p>Jovanka Placeres</p>
            </div>
          </div>

      </div>

  </div>

<!--this break brings up page content above footer at normal/standard viewing size -->
<br class="clr" />
    
  

app/views/games/show.html.erb
<div>
  <a name="chess-game"><p class="invisible-text">!</p></a>
  <br class="clr" />

  <div class="game-interface col-xs-10 col-xs-offset-1">

    <div class="col-xs-8">
      <div class="game-background">
        <br class="clr" />

        <div class="chessboard board">
          <% (0..7).each do |y| %>
            <% (0..7).each do |x| %>
              <% if (x.even? && y.odd?) || (x.odd? && y.even?) %>

                <div class="black-tile tile" data-coordinates="<%= "#{x},#{(y-7).abs}" %>">
                  <div class="piece" data-piece-type="<%= piece_type(x,(y-7).abs) %>" data-piece-color="<%= piece_color(x,(y-7).abs) %>" data-update-url="<%= update_url(x,(y-7).abs) %>">
                      <%= render_piece(current_game, x,(y-7).abs) %>
                  </div>
                </div>

              <% else %>

                <div class="white-tile tile" data-coordinates="<%= "#{x},#{(y-7).abs}" %>"> 
                  <div class="piece" data-piece-type="<%= piece_type(x,(y-7).abs) %>" data-piece-color="<%= piece_color(x,(y-7).abs) %>" data-update-url="<%= update_url(x,(y-7).abs) %>">
                    <%= render_piece(current_game, x,(y-7).abs) %>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
          <br class="clr" />
        </div> <!-- chessboard -->
      </div>
    </div>


    <div class="col-xs-4">
      <br class="clr" />
      <div class="panel panel-default shadow">
        <div class="panel-heading">
          <h3 class="panel-title text-center"><%= current_game.name %></h3>
        </div>
        <div class="panel-body">
          <div>
            <div class="col-xs-4 text-center">
              <div id="portrait1" class="<%= gravatar_class('white') %>">   
                <%= image_tag player('white').gravatar_url if player('white').present? %>
              </div>
              <h5 class="invisible-text"><%= "?" if player('white').nil? %></h5>
              <h5><%= player('white').username if player('white').present? %></h5>
              <hr class="hr-style">
              <small>white</small>
            </div>
            <div class="col-xs-4 text-center">
              <h1>vs.</h1>
            </div>
            <div class="col-xs-4 text-center">
              <div id="portrait2" class="<%= gravatar_class('black') %>">            
                <%= image_tag player('black').gravatar_url if player('black').present? %>
              </div>
              <h5 class="invisible-text"><%= "?" if player('black').nil? %></h5>
              <h5><%= player('black').username if player('black').present? %></h5>
              <hr class="hr-style">
              <small>black</small>
            </div>
            <br class="clr" /><br/>
            <div>
              <p><%= current_game.status %></p>
              <p id="game-turn" class="turn text-center"><%= current_game.turn.capitalize %> player's turn!</p>
              <br/>
              <button type="button" class="btn btn-danger">Forfeit</button>
              <!--%= link_to 'Forfeit', forfeit_game_path(current_game), method: :put, class: "btn btn-danger", data:  {confirm: "Are you sure you want to forfeit?"} %> -->
            </div>
          <div>
        </div>
      </div>
    </div>
  </div>

  <br class="clr" />
  <br class="clr" />
  <br class="clr" />
</div>

<br class="clr" />
<div id="dialog-black">
  <div class="dialog-tile queen">
    <%= "\u265B".encode('utf-8') %>
  </div>
  <div class="dialog-tile rook">
    <%= "\u265C".encode('utf-8') %>
  </div>
  <div class="dialog-tile bishop">
    <%= "\u265D".encode('utf-8') %>
  </div>
  <div class="dialog-tile knight">
    <%= "\u265E".encode('utf-8') %>
  </div>
</div>

<div id="dialog-white">
  <div class="dialog-tile queen">
    <%= "\u2655".encode('utf-8') %>
  </div>
  <div class="dialog-tile rook">
    <%= "\u2656".encode('utf-8') %>
  </div>
  <div class="dialog-tile bishop">
    <%= "\u2657".encode('utf-8') %>
  </div>
  <div class="dialog-tile knight">
    <%= "\u2658".encode('utf-8') %>
  </div>
</div>

<!-- -->

<script>
  $(function(){
    $('.piece').css('cursor', 'pointer');
    $('.dialog-tile').css('cursor', 'pointer');
    // add class to piece to indicate it can be removed (can-be-captured) and that it is pre-rendered (static)
    $('.piece').addClass('can-be-captured static'); 

    $('.piece').draggable({
      containment: '.board',
      cursorAt: { top: 60, left: 56 },
      snap: '.tile', 
      revert: 'invalid',
      start: function(event, ui) {
        drag_position = ui.position;
        
        // ajax --> pieces#show (renders text of valid moves) --> highlight those moves
        $.ajax({
          type: 'GET',
          url: $(this).data('update-url'),
        }).done(function(r) {
          if ( r.length > 0 ) {
            valid_moves = JSON.parse(r);
            var target;
            arrayLength = valid_moves.length;
            for (var i = 0; i < arrayLength; i++) {
              target = valid_moves[i].toString();
              $('.tile[data-coordinates="'+ target +'"]').addClass('highlight-light')

              // droppable
              $('.tile[data-coordinates="'+ target +'"]').droppable({
                // accept: $('.piece'),  // 
                drop: function(event, ui) {
                  ui.draggable.position( { of: $(this), my: 'left top', at: 'left top' } );
                  updatePieceLocation(event, ui); 
                  // $('.tile').removeClass('ui-droppable');  //
                }
              });
            } // for
          } // if
        }).fail(function (x, t, e) {
          console.log(e);
        });
      }, //start
      stop: function() {
        $('.tile').removeClass('highlight-light');
      }   
    }); 
    
    function updatePieceLocation(event, ui) {
      x = event.target.dataset.coordinates[0];
      y = event.target.dataset.coordinates[2];
      promotion_choice = 'Queen';
      
      // (1) BUG! - dialog displays when pawn is dragged to a tile with correct y location 
      // ( --> want it only to display when dragged to valid move x, y location)
      // (2) code below can probably be refactored

      if (ui.draggable.data('piece-type') == 'Pawn' && ui.draggable.data('piece-color') == 'white' && y == 7 && $('#game-turn').text()[0] == 'W') {
        displayWhiteDialogBox(ui);
        $('.queen').click( function() { 
          promotion_choice = 'Queen';
          ajaxPiecesUpdateCall(event, ui);
          $('.piece').draggable( 'enable' );
          $('#dialog-white').dialog('close');
        });
        $('.rook').click( function() { 
          promotion_choice = 'Rook';
          ajaxPiecesUpdateCall(event, ui);
          $('.piece').draggable( 'enable' );
          $('#dialog-white').dialog('close');
        });
        $('.bishop').click( function() { 
          promotion_choice = 'Bishop';
          ajaxPiecesUpdateCall(event, ui);
          $('.piece').draggable( 'enable' );
          $('#dialog-white').dialog('close');
        });
        $('.knight').click( function() { 
          promotion_choice = 'Knight';
          ajaxPiecesUpdateCall(event, ui);
          $('.piece').draggable( 'enable' );
          $('#dialog-white').dialog('close');
        });
      }
      else if (ui.draggable.data('piece-type') == 'Pawn' && ui.draggable.data('piece-color') == 'black' && y == 0 && $('#game-turn').text()[0] == 'B') {
        displayBlackDialogBox(ui);
        $('.queen').click( function() { 
          promotion_choice = 'Queen';
          ajaxPiecesUpdateCall(event, ui);
          $('.piece').draggable( 'enable' );
          $('#dialog-black').dialog('close');
        });
        $('.rook').click( function() { 
          promotion_choice = 'Rook';
          ajaxPiecesUpdateCall(event, ui);
          $('.piece').draggable( 'enable' );
          $('#dialog-black').dialog('close');
        });
        $('.bishop').click( function() { 
          promotion_choice = 'Bishop';
          ajaxPiecesUpdateCall(event, ui);
          $('.piece').draggable( 'enable' );
          $('#dialog-black').dialog('close');
        });
        $('.knight').click( function() { 
          promotion_choice = 'Knight';
          ajaxPiecesUpdateCall(event, ui);
          $('.piece').draggable( 'enable' );
          $('#dialog-black').dialog('close');
        });
      }
      else {
        ajaxPiecesUpdateCall(event, ui)
      }       
    } // updatePieceLocation

    // ajax ==> pieces#update
    function ajaxPiecesUpdateCall(event, ui) {
      $.ajax({
        type: 'PUT',
        url: ui.draggable.data('update-url'),
        dataType: 'text',
        data: { x_pos: x, y_pos: y, choice: promotion_choice }
      }).done(function(r) {
        // "reset" piece (can be captured, static, & any added prior location class removed)
        ui.draggable.attr('class', 'piece ui-draggable ui-draggable-handle') 
        ui.draggable.addClass(x+y);   // add class to piece to indicate current location
        // piece removal 
        $('.can-be-captured'+'.'+x+y).remove();  // remove any previously dragged piece at this location
        $(event.target).find('div.can-be-captured.static').remove();  // remove pre-rendered piece 
        // "re-enable" piece for future removal
        ui.draggable.addClass('can-be-captured'); 
        // update turn on page
        $('#portrait1,#portrait2').toggleClass('highlight-turn');
        $('#game-turn').text($('#game-turn').text() == "White player's turn!" ? "Black player's turn!" : "White player's turn!");
        // update pawn piece to reflect pawn promotion 
        if (r[0] == 'p') {
          ui.draggable.data('piece-type', r.substring(3));
          ui.draggable.text(r[2]);
        }
        // update static rook pieces to reflect castling
        if (r[0] == 'c') {
          if (x == '6' && y == '0') { $('.tile[data-coordinates="7,0"]').find('div.static').css({left: -160}) }
          if (x == '6' && y == '7') { $('.tile[data-coordinates="7,7"]').find('div.static').css({left: -160}) }
          if (x == '2' && y == '0') { $('.tile[data-coordinates="0,0"]').find('div.static').css({left: +240}) }
          if (x == '2' && y == '7') { $('.tile[data-coordinates="0,7"]').find('div.static').css({left: +240}) }
        }
      }).fail(function (x, t, e) {
        // revert draggable (piece) on ajax call failure 
        // (3) The 4 lines below are important for reverting piece back to where it was when player tries to
        //     drag it around when it's not their turn, not a valid move, or otherwise forbidden move
        //     However, it causes massive visual bugs when when a 2nd pawn piece is promoted...
        //     All previous ui-draggable appear to reset their position relative to tile of that promotion
        // (4) Disabling the lines below prevents the visual bugs caused by 2nd+ pawn promotion, but leaves
        //     game vulnerable to player randoming moving pieces anywhere 
        // ui.draggable.css({
        //   'left': drag_position.left,
        //   'top': drag_position.top
        // });
      });
    } // ajaxPiecesUpdateCall
    
    function displayBlackDialogBox(ui) {
      $('#dialog-black').dialog({
        resizable: false,
        width: 360,
        minHeight: 90,
        position: { of: ui.draggable, my: 'left+12 top', at: 'left top-96' }
      }); 
      $(".ui-dialog-titlebar").hide();
      $(".ui-dialog-buttonpane").hide();
      $(".ui-dialog").css({'background': '#f5eacd', 'border': '1px solid #293e6a'});
      $(".ui-dialog-content").css('background', '#f5eacd');
      $('.piece').draggable( 'disable' ); // temporarily disable dragging pieces 
    } // displayBlackDialogBox

    function displayWhiteDialogBox(ui) {
      $('#dialog-white').dialog({
        resizable: false,
        width: 360,
        minHeight: 90,
        position: { of: ui.draggable, my: 'left+12 top', at: 'left bottom' }
      }); 
      $(".ui-dialog-titlebar").hide();
      $(".ui-dialog-buttonpane").hide();
      $(".ui-dialog").css({'background': '#f5eacd', 'border': '1px solid #293e6a'});
      $(".ui-dialog-content").css('background', '#f5eacd');
      $('.piece').draggable( 'disable' ); // temporarily disable dragging pieces 
    } // displayWhiteDialogBox
 
    $('.dialog-tile').hover(
      function() {
        $( this ).addClass( 'highlight-dark' );
      }, function() {
        $( this ).removeClass( 'highlight-dark' );
      }
    );

    // Forfeit 
    $('.btn-danger').click(function(){
      if (confirm('Are you sure you want to forfeit?')) {
        $.ajax({
          type: 'PUT',
          url: "<%= forfeit_game_path(current_game) %>",
          success: function(r) {
            $('#game-turn').removeClass('turn');
            $('#game-turn').addClass('forfeit');
            $('#game-turn').text(r);
          },
          error: function() {
            alert("You cannot forfeit a game that has status: <%= current_game.status %>!");
          }
        });
      };
    });

  }); // function

</script>