config/routes.rb
KnightsChess::Application.routes.draw do
  devise_for :users
  root 'games#index'
  resources :games do
    resources :pieces, only: [:show, :update]
    member do
      put :forfeit
    end
  end
  resources :players, only: [:index, :edit, :update, :show] do
    collection do
      put :delete_user
      put :change_nickname
    end
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  require 'gchart'

  before_action :check_admin, only: [:index, :edit, :update, :delete_user]

  def index
    @users = User.all
    @games = Game.all
  end

  def show
    @user = User.find(params[:id])
    @games = Game.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    redirect_to players_path
  end

  def delete_user
    User.find(params[:user_to_delete]).destroy
    redirect_to players_path
  end

  def change_nickname
    @user = User.find(current_user.id)
    @user.update_attributes(user_params)
    redirect_to player_path(@user)
  end

  private

  def check_admin
    return render_not_found(:forbidden) unless !current_user.nil? && current_user.admin?
  end

  def user_params
    params.require(:user).permit(
      :games_as_white, :won_games, :won_games_as_white, :lost_games, :lost_games_via_forfeit, :tied_games,
      :admin, :username
    )
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_tag(delete_user_players_path, :method => :put) do %>
  <%= hidden_field_tag :user_to_delete, u.id %>
  <%= submit_tag 'x', data: { confirm: "Are you sure you want to delete #{u.username}?" }, class: "btn btn-danger btn-sm" %>
<% end %>

app/views/players/edit.html.erb
<br/>
<div class="col-md-10 col-md-offset-1">
  <div class="form-background">
    <h1>Edit User</h1>
    <div>
      <%= simple_form_for @user, :url => player_path(@user), :method => :put do |f| %>
        <%= f.input :games_as_white %>
        <%= f.input :won_games_as_white %>
        <%= f.input :won_games %>
        <%= f.input :lost_games %>
        <%= f.input :tied_games %>
        <%= f.input :lost_games_via_forfeit %>
        <%= f.input :admin %>
        <br/>
        <%= f.submit 'Update' %>
      <% end %>
    </div>
  </div>
</div>

app/views/players/index.html.erb
<br class="clr"/>
<div class="manage-users col-xs-10 col-xs-offset-1">
  <h1>All Users</h1>
  <div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>ID</th> 
          <th>Email</th>
          <th>Edit user...</th>  
          <th>Admin</th>
          <th>G/w</th>  
          <th>W/w</th>
          <th>W</th>  
          <th>L</th>  
          <th>D</th>  
          <th>L/f</th>
          <th>Delete</th>       
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr> 
            <td><%= link_to "#{user.id}", player_path(user) %></td>
            <td><%= user.email %></td> 
            <td><%= link_to "#{user.username}", edit_player_path(user) %></td>
            <td><%= user.admin %></td>
            <td><%= user.games_as_white %></td>
            <td><%= user.won_games_as_white %></td>
            <td><%= user.won_games %></td>
            <td><%= user.lost_games %></td>
            <td><%= user.tied_games %></td>
            <td><%= user.lost_games_via_forfeit %></td> 
            <td><%= render partial: 'players/form', locals: { u: user } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br class="clr" />
  <hr class="hr-style"/>
  <h1>All Games</h1>
  <div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>ID</th> 
          <th>Name</th> 
          <th>Status</th>
          <th>Inspect</th>  
          <th>Delete</th>      
        </tr>
      </thead>
      <tbody>
        <% @games.each do |game| %>
          <tr>
            <td><%= link_to "#{game.id}", game_path(game) %></td>
            <td><%= game.name %></td>
            <td><%= game.status %></td>
            <td><%= game.inspect %></td>
            <td><%= link_to 'x', game_path(game), method: :delete, data: { confirm: "Are you sure you want to delete game #{game.name}?" }, class: "btn btn-danger btn-sm"  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <div>
  </div>
</div>

app/views/players/show.html.erb
<br class="clr" />
<div class="user-dashboard col-xs-10 col-xs-offset-1">
  <% if current_user != nil && current_user.id == @user.id %>
    <h1>My Dashboard</h1>
    <hr class="hr-style"/>
  <% end %>
  <br class="clr" />
  <div>
    <div class="col-xs-4 col-sm-3">
      <%= image_tag @user.gravatar_url %>
    </div>
    <div class="col-xs-8 col-sm-9">
      <h3><%= @user.username %></h3>
      <p id="edit-nickname">
        <% if current_user != nil && current_user.id == @user.id %>
          <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
            Change nickname
          </button>
        <% end %>
      </p>
    </div>
  </div>
  <br class="clr" />
  <hr class="hr-style"/>
  <br class="clr" />

  <% draw_win_lose = [ @user.tied_games, @user.won_games, @user.lost_games ].map! { |x| if x.nil? then x = 0 end } %>
  <% games_played = draw_win_lose.inject(0, :+) %>
  <% games_played_as_black = games_played - @user.games_as_white.to_i %>
  <% win_rate = @user.won_games.to_f / games_played.to_f * 100 %>
  <% win_rate_as_white = @user.won_games_as_white.to_f / @user.games_as_white.to_f * 100 %>
  <% win_rate_as_black = (@user.won_games.to_i - @user.won_games_as_white.to_i).to_f / games_played_as_black.to_f * 100 %>
  <% total_white_black = [ games_played, @user.games_as_white, games_played_as_black ] %>

  <div>
    <div class="col-xs-12 col-sm-6 col-md-4 text-center">
      <div class="thumbnail">  
        <%= image_tag(Gchart.bar(
          title: 'Games Played',
          data: total_white_black,
          labels: ["total (#{games_played})", "white (#{@user.games_as_white})", "black (#{games_played_as_black})"],
          bar_width_and_spacing: '75,20')) %>
      </div>
    </div> 
    <div class="col-xs-12 col-sm-6 col-md-4 text-center">
      <div class="thumbnail">
        <%= image_tag(Gchart.pie(
          title: 'Wins / Loses / Draws',
          labels: ["drawn (#{@user.tied_games})", "won (#{@user.won_games})", "lost (#{@user.lost_games})"],
          data: draw_win_lose)) %>
      </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 text-center">
      <div class="thumbnail text-left">
        <div class="stats-box">
          <% if current_user != nil && current_user.id == @user.id %>
            <h4>My Stats</h4>
          <% else %>
            <h4><%= "#{@user.username}'s stats"%></h4>
          <% end %>
          <hr class="hr-style"/>
          <p>Win rate: &nbsp; <b><%= "#{'%.02f' % win_rate}%"%></b></p>
          <p>Win rate as white: &nbsp; <b><%= "#{'%.02f' % win_rate_as_white}%"%></b></p>
          <p>Win rate as black: &nbsp; <b><%= "#{'%.02f' % win_rate_as_black}%"%></b></p>   
          <p>Games lost via forfeit: &nbsp; <b><%= "#{@user.lost_games_via_forfeit}" %></b> of <%= "#{@user.lost_games}"%></p>
        </div>
      </div>
    </div> 
  </div>

  <% user_games_as_white = @games.where(player_white_id: @user.id) %>
  <% user_games_as_black = @games.where(player_black_id: @user.id) %>
  <br class="clr" />
  <hr class="hr-style"/>
  <% if current_user != nil && current_user.id == @user.id %>
    <h2>My Games</h2>
  <% else %>
    <h2><%= "#{@user.username}'s Games"%></h2>
  <% end %>
  <br class="clr" />
    
  <div class="user-dashboard-games-table">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Opponent</th>
          <th>Status</th>
          <th>Winning Player</th>
        </tr>
      </thead>
      <tbody>
        <% user_games_as_white.each do |game| %>
          <tr>
            <td>
              <%= link_to "#{game.name}", game_path(game) %>
              <% if current_user.id != nil && game.user_id == current_user.id %>
                <%= " | " %>
                <%= link_to 'edit', edit_game_path(game) %>
                <% if game.status == 'open' %>
                  <%= " | " %>
                  <%= link_to 'delete', game_path(game), method: :delete, data: { confirm: "Are you sure you want to delete game #{game.name}?" }%> 
                <% end %>
              <% end %>    
            </td>
            <td><%= User.find(game.player_black_id).username if game.player_black_id != nil %></td>
            <td><%= game.status %></td>
            <td><%= game.winning_player_id %></td>
          <tr>
        <% end %>
        <% user_games_as_black.each do |game| %>
          <tr>
            <td>
              <%= link_to "#{game.name}", game_path(game) %>
              <% if current_user.id != nil && game.user_id == current_user.id %>
                <%= " | " %>
                <%= link_to 'edit', edit_game_path(game) %>
                <% if game.status == 'open' %>
                  <%= " | " %>
                  <%= link_to 'delete', game_path(game), method: :delete, data: { confirm: "Are you sure you want to delete game #{game.name}?" }%> 
                <% end %>
              <% end %>  
            </td>
            <td><%= User.find(game.player_white_id).username if game.player_white_id != nil %></td>
            <td><%= game.status %></td>
            <td><%= User.find(game.winning_player_id).username if game.winning_player_id != nil %></td>
          <tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <br class="clr" />
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Change nickname</h4>
      </div>
      <%= simple_form_for @user, :url => change_nickname_players_path, :method => :put do |f| %>
        <div class="modal-body">
          <%= f.input :username, label: 'Nickname' %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= submit_tag 'Save', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>