config/routes.rb
KnightsChess::Application.routes.draw do
  devise_for :users
  root 'games#index'
  resources :games do
    resources :pieces, only: [:show, :update]
    member do
      put :forfeit
    end
  end
  resources :players, only: [:index, :edit, :update, :show] do
    collection do
      put :delete_user
      put :change_nickname
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KnightsChess</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  
  <body>
  
  <div id="wrap">  
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Knights of Ren', root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <!--ul class="nav navbar-nav">
            <li>
              <a href="https://github.com/KnightsofRen/knights_chess" >
                <!--small>by KnightsofRen</small-->
                <!--i class="fa fa-github"></i>
              </a>
            </li> 
          </ul-->
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= image_tag current_user.gravatar_url(size: 30), id: "avatar" %>
                  <%= current_user.username %>
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <% if current_user.admin? %>
                    <li><%= link_to 'Manage app', players_path %></li>
                  <% end %>
                  <li><%= link_to 'My Dashboard', player_path(current_user) %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
              <li id="user-sign-up"><%= link_to 'Sign up', new_user_registration_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>


    <% if notice.present? %>
      <p class="alert alert-info" role="alert"><%= notice %></p>
    <% end %>

    <% if alert.present? %>
      <p class="alert alert-danger" role="alert"><%= alert %></p>
    <% end %>
    
    <%= yield %>
  </div>
 

    <!--- FOOTER -->
    <br class="clr" />

    <div id="footer">
      <div class="container">
        <div class="text-center">
          <br />
          Knights of Ren
          <%= link_to 'https://github.com/KnightsofRen/knights_chess' do %>
            <%=image_tag 'gitpic.png', class: 'social-button' %>
          <% end %>
          <br /><br />
        </div>
      </div>
    </div>

 
  </body>
</html>